apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: flux-system
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: registry.gitlab.com/YOUR_GROUP/app-repo:PLACEHOLDER
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: flux-system
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8083
  type: ClusterIP
